server:
  port: 8082
spring:
  application:
    name: InventoryService
  datasource:
    url: jdbc:postgresql://localhost:16543/inventory_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  observations:
    key-values:
      application: InventoryService
  tracing:
    sampling:
      probability: 1.0 # 100% of traces will be sampled