apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak
          ports:
            - containerPort: 7080
          args: [ "start-dev", "--import-realm" ]
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  key: KC_DB
                  name: keycloak-realm-config
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_URL
                  name: keycloak-realm-config
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_USERNAME
                  name: keycloak-realm-config
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KC_DB_PASSWORD
                  name: keycloak-admin-secret
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: keycloak-realm-config
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: keycloak-admin-secret
            - name: KC_HOSTNAME
              value: "localhost"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_LOG_LEVEL
              value: "info"
          volumeMounts:
              - mountPath: /opt/keycloak/data/import
                name: keycloak-realm
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm-config