server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:15432/order_service
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
inventory-service:
  url: http://localhost:8082
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs