global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  # Default job by prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  # Product service job
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## in prod, instead of host.docker.internal put product service container name
        labels:
          applcation: 'Product service'
  # Order service job
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          applcation: 'Order service'
  # Inventory service job
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          applcation: 'Inventory service'
  # Notification service job
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          applcation: 'Notification service'
  # API-gateway job
  - job_name: 'api-gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9000' ]